# Generated by Django 5.2.13 on 2026-04-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collectoruser_packagesession_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectoruser',
            options={'ordering': ['email', 'firebase_uid'], 'verbose_name': 'Пользователь (Firebase)', 'verbose_name_plural': 'Пользователи (Firebase)'},
        ),
    ]
