# Generated by Django 5.2.13 on 2026-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_database_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectoruser',
            name='admin_projects',
            field=models.ManyToManyField(blank=True, help_text='Веб /ui/packages/ — Firebase-вход, только отмеченные проекты.', related_name='admin_collector_users', to='api.project', verbose_name='Доступные проекты (Client-admin)'),
        ),
        migrations.DeleteModel(
            name='UiUserProfile',
        ),
    ]
